---
resources:
- name: fanmerge
  type: git
  source:
    uri: https://github.com/andrew-edgar/fanmerge
- check_every: 1h
  name: pipeline-image
  source:
    password: ((concourse-ci-bot-apikey))
    repository: uk.icr.io/concourse/kubecf-base-image
    tag: latest
    username: iamapikey
  type: docker-image

jobs:
- name: build-coredns
  public: true
  plan:
  - get: fanmerge
  - get: pipeline-image
  - task: do-build
    image: pipeline-image
    params:
      DOCKER_API_KEY: ((coligo-test-apikey))
    privileged: true
    config:
      inputs:
      - name: fanmerge
      platform: linux
      run:
        path: /bin/bash
        args:
        - -ec
        - |
          # Start Docker Daemon (and set a trap to stop it once this script is done)
          echo 'DOCKER_OPTS="--data-root /scratch/docker --max-concurrent-downloads 10"' > /etc/default/docker
          service docker start
          service docker status
          trap 'service docker stop' EXIT
          sleep 10

          echo $GOPATH
          pushd $GOPATH
            git clone https://github.com/coredns/coredns
            cd coredns
            git checkout v1.7.1
            echo fanmerge:github.com/andrew-edgar/fanmerge >> plugin.cfg
            make
          popd
          cp fanmerge/coredns/buildResources/Makefile.release $GOPATH/coredns
          pushd $GOPATH/coredns
            make -f Makefile.release release
            make -f Makefile.release docker

            docker login -u iamapikey -p $DOCKER_API_KEY us.icr.io
            docker push us.icr.io/codeengine-relint/coredns:coredns-amd64
          popd
